Repository RoboStack/jupyter-ros, pull requests merged in 2022-08, with the labels that each got.

#116 Import ROS1 or ROS2 modules based on environment
  jupyros/__init__.py
Labels: enhancement

#117 Rename `client` to `service_client`
  docs/source/user_ros_essentials.rst
  jupyros/ros1/ros_widgets.py
  notebooks/ROS_Services_Clients.ipynb
Labels: enhancement, documentation

#118 Added build workflow
  .github/workflows/build.yml
Labels: maintenance

#119 Ros2 scalable
  jupyros/ros2/__init__.py
  jupyros/ros2/publisher.py
  jupyros/ros2/ros_widgets.py
  jupyros/ros2/subscriber.py
  notebooks/Ros2 Pub_Sub_Communication.ipynb
Labels: enhancement

#114 Adopt jupyter-releaser
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  CHANGELOG.md
  MANIFEST.in
  js/package.json
  jupyros/__init__.py
  jupyros/_version.py
  jupyros/ros1/ros3d.py
  pyproject.toml
  scripts/bump-version.py
  setup.cfg
  setup.py
Labels: enhancement

#123 Automated Changelog Entry for 0.6.0a0 on master
  CHANGELOG.md
Labels: documentation
