Repository RoboStack/jupyter-ros, pull requests merged in 2023-03, with the labels that each got.

#148 Update check-release
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .gitignore
  MANIFEST.in
  js/package.json
  js/yarn.lock
  jupyros/__init__.py
  jupyros/_version.py
  jupyros/ros1/ros3d.py
  jupyros/ros1/server_extension.py
  jupyter-config/jupyros_nbserver_extension.json
  jupyter-config/jupyros_server_extension copy.json
  jupyter-config/jupyter-ros.json
  pyproject.toml
  scripts/bump-version.py
  setup.cfg
  setup.py
Labels: maintenance

#142 Turtle
  jupyros/__init__.py
  jupyros/ros2/__init__.py
  jupyros/ros2/ipy.py
  jupyros/ros2/publisher.py
  jupyros/ros2/turtle_sim.py
  notebooks/ROS2_Turtlesim.ipynb
  notebooks/ROS2_Turtlesim_KeyboardControl.ipynb
Labels: enhancement

#149 Automated Changelog Entry for 0.7.0a0 on main
  CHANGELOG.md
Labels: documentation
